apiVersion: v1
appName: solar-system-app

service:
  type: ClusterIP
  port: 5000

deployment:
  replicas: 3
  repository:
    name: ofekgoldstein
    image: final-project
    tag: 1.0.133

mongo:
  app_secret_key: zaza7531
  uri: mongodb://ofek:ofek2002@mongodb:27017/?authSource=Final-project