apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000 #{{ .Values.service.port }}
      targetPort: 5000 #{{ .Values.service.port }}
      protocol: TCP
      name: http