apiVersion: v1
kind: Service
metadata:
  name: final-project-service
spec:
  selector:
    app: final_project
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
