apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.deployment.repository.name }}/{{ .Values.deployment.repository.image }}:{{ .Values.deployment.repository.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: APP_SECRET_KEY
             # value: "zaza7531"
              value: "{{ .Values.mongo.app_secret_key}}"
            - name: MONGO_URI
              #value: "mongodb://ofek:ofek2002@mongodb:27017/?authSource=Final-project"
              value: "{{ .Values.mongo.uri}}" 